title: Xing Dai's Homepage
page-top-title: Xing Dai
top-section-bg-text: Undergraduate student of Information and Computing Science
home-subtitle: Xing Dai&ensp;|&ensp;戴兴
copyright-text: '&copy; Xing Dai 2023-2025. All Rights Reserved.'
